# 文本分类

In [1]:
import pandas as pd

from transformers import AutoTokenizer

data = pd.read_csv('ChnSentiCorp_htl_all.csv')
data

D:\PycharmProjects\llm_sft\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7766 rows x 2 columns]

In [2]:
data = data.dropna()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7765 rows x 2 columns]

## 创建Dataset

In [3]:
from torch.utils.data import Dataset


class MyDataset(Dataset):
    def __init__(self):
        super().__init__()
        self.data = pd.read_csv('ChnSentiCorp_htl_all.csv')
        self.data = self.data.dropna()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data.iloc[index]['review'], self.data.iloc[index]['label']

In [4]:
dataset = MyDataset()

for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', 1)
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', 1)
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', 1)
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', 1)
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', 1)

In [5]:
from torch.utils.data import random_split

train_set, valid_set = random_split(dataset, [0.9, 0.1])
len(train_set), len(valid_set)

(6989, 776)

In [6]:
for i in range(10):
    print(train_set[i])

('去的时候已经很晚了，在大厅叫了好几声才有一个服务员从前台后面爬起来，帮忙办理了入住手续。进到房间后发现房间的设施非常简陋，霉味也非常大。第二天早上起来才仔细看了一下房间，比起如家等快捷酒店差远了，说是三星的酒店，但距离三星不是差一点点。。。根本对不起220的价格，最多也就值100多一点点。', 0)
('这是我在携程遇到过的最差的酒店，问题多多1.这大冷天的。房间塑钢窗密封性极差，四处漏风，第二天换了个房间，也漏，不过比上一间漏的小点，联系服务员，服务员跟我说你自己拿透明胶条把缝粘粘就行2.暖气不热。服务员告知本酒店采用地暖方式，我一点没体会到地暖的优越性，在房间呆着需要靠羽绒服保暖，晚上睡觉需要盖2床被子3.浴室里淋浴的水时冷时热。水及不稳定，又时候冰你一下，有时候烫你一下4.房间里的空调禁止使用。从一进屋我就开始找空调遥控器，没找到，遂联系服务员，被告知由于我店采用地暖，空调暖风可以不用，遥控器由酒店统一保管。几经交涉终于把遥控器要到手了。。想要点暖风真不容易啊5.饭菜质量差。18一位的自助午餐，要了一份猪蹄，刚吃几口发现猪蹄上还有好多没拔干净的毛。。。。。宾馆反馈2008年6月10日：1、关于用水：经过我们认真的检查，我们最终确定造成洗浴水温波动的主要原因是冷水的压力变动。邯郸市自来水管网中的水压在用水峰谷压力不稳定，酒店专用自来水入户表井口径是50的，用水量不够使用。我们采取了以下措施：1、向邯郸市自来水公司申请扩容，安装直径100的入户表井，保证用水量，目前已完成。在管网中增加自动管道加压泵，保证恒定的管网压力，目前已完成。3、增加管网末端稳压水箱，体积3.3立方。经过以上措施彻底保证管网压力稳定。2、关于窗体密封：关于部分双层隔音窗密封问题，我酒店积极和施工单位进行协调，采取方法加以改善：更换部分窗扇的密封条。修复损坏失效的五金件。对窗体和楼体的接触部分，从内部进行密封胶密封，从外部进行玻璃胶密封。以上措施，业已落实到位，效果明显。3、关于地采暖：对于燕赵之星开业以来的第一个冬季，我们在取暖工作上的确出现了一些问题。首先是，我们对采暖系统的操作上经验不足，设备运能不能完全发挥，对此，我们积极联系厂家和专业维修人员进行设备调试。另外我们对具体操作的员工进行了调整和培训，制定完善了操作规程，明确了岗位责任。同时，我们对原煤供货商进行了调整，采购热能更高，更加洁净的白煤用于取暖。对于我们前一个采暖季节出现的问题，再次对各位信任我们的朋友，致以真诚的歉意，希望大家能再次信任我们。4、我们将继续努力：以上都是在燕赵之星商务酒店开业过程中，我们所面临的困难。随着燕赵之星步入第二个经营年，各项设施设备的完善，人员配备和培训的加强，我们正在全面的解决这些问题。感谢始终关注我们的各位朋友，您的批评指正是我们前进的动力。我们乐于通过自己的努力，为各位朋友在邯郸市营建一个温馨的家。', 0)
('美仑大酒店我第2次去住了。首先需要肯定的是，客服布置非常不错，很高雅，尤其是床铺，特别舒服特别柔软。我特意掀开床罩开了一下，美伦酒店的床的床垫很有可能是特别定制的。床垫下方和上面都特别有一层软垫连在一起。所以睡上去才会这样舒服。特别赞一个。不过美中不足的是，美伦酒店的房件隔音有点问题。一般酒店房间隔音分为3部分，窗外隔音，走道门隔音和邻间隔音。前面两个没啥好讲的，窗外隔音不错。但问题出在邻间隔音上。美伦酒店的房间，两间之间有一部分是衣厨相连的，没有实心墙，衣厨一划两半，一半这间一半那间。只有薄薄的木板隔开。所以邻间隔音简直是恶梦！隔壁房间住人进来的讲话声，还有他们拉开衣服挂衣服衣架撞击厨壁，声音响得不得了。把我从午睡当中吵醒！如果你隔壁房间住了吵杂的人，那你简直就别想休息好。如果你想在房间“激情”一下，也请千万小心哦，隔壁会听到！交通方面一般，离地铁站较远。不过购物还好，出门就有乐购商场。另外特别赞一下，美伦的早餐自助餐，真是太棒了，样式特别丰富，而且特别好吃。档次很高！特别美味。来美仑住，一定要享受他们的早餐自助餐！顺便说一下，本人懂卫视。本人发现美伦的卫星电视貌似用了盗版卫星电视。因为根据国家法律，星级酒店用的是“统一平台”即134号卫星上的国家批准的落地平台，但我发现美伦只有HBO是“统一平台”上的HBO（带简体中文字幕），其他的境外台居然都是从146号菲律宾卫星上引下来的盗版台！cinemax不带中文字幕！还有CNN、BBC，都是从146号菲星上引下来的！这几天菲星上的台，底下都有菲律宾卫视商打上去的游动字幕广告（是奥运频道的广告），全都一字不漏出来了！我知道“统一平台”分配给酒店一般只有一张卡，但是，拜托，美仑的技术人员难道不知道有一种设备叫做“分卡器”吗？而且唯一的正版境外台HBO，还时有马赛克，看来美伦酒店对准134的天线没有完全对准哦。其他的还包括，马桶圈垫上有渍，叫服务员来看过，说是以前消毒剂留下来的痕迹。当着我的面再次消毒一次，那个痕迹确实消不掉。不过拜托，不能直接换掉马桶盖吗？又不贵！那个坐垫圈上消不掉的渍子真的好讨厌哦，估计每次入住的客人都会叫服务员过来看一下。美伦不嫌烦吗？另外我房间的电视遥控器按键有一个不灵。就是选台键，只有上翻，下翻键没反应。估计遥控器使用得时间太长内部已经不行了。另外宽带很贵，计时价，每分钟1元，100元封顶。虽然速度不错，但价钱不便宜哦', 1)
('我们是今年五一期间入住酒店的标间，卫生一般，房间有点异味。酒店对面有个超市，要买东东要赶早，好像晚上8点多就关门了。晚上路边小吃很多。', 0)
('前几次入住此酒店的舒适感觉使我认为再去香港住这是必然的选择，现在看来现实真是太残酷了！！！-中午到达酒店办理入住手续时开始出问题：找不到入住的人名；好不容易找着了人名房型又不对，酒店前台服务员板着脸说是携程跟他们定房间时没有说明，不能调换房间，经过来来回回两个多小时的三方交涉，酒店给了我们一张免费的加床并说第二天给调换房间，后来就没人搭理我们了，结果是我们住了四天的加床，直到第五天时我们换了一家公司定房，酒店才给调了我们需要的房间，终于结束了这几天的加床之旅。酒店前台服务员态度生硬，房间的超迷你和以前住在这时有着鲜明的反差，这使我感受到了美好的东西也不是一成不变的，多一些其他的选择是应变的最好办法。', 0)
('一个月前入住过，首先是装修已经很陈旧了，给人一种死气沉沉的感觉，再就是服务，都是大妈级的，倒退10年还能算4星，现在很难说了。', 0)
('澳门本来就小所以地理位置没什么好说的所有码头都有开往各大酒店的巴士这间酒店大堂还可以房间一般而且没什么景观可言里面的菲佣招待好像听不懂普通话只懂粤语和英文.我倒是看见渔人码头里有一家新开的白色建筑酒店西式的英文名叫Rocks&Hotel面对大海和大桥.想必还是不错的.有意向的朋友可以一查.', 1)
('宾馆的周边环境比较好，只是隔墙有个大型公交停车场，有点吵。可能这宾馆有很多长租的客人，很多房间的门上都粘了纸信箱，感觉有点怪怪的。房间的装修很旧，没有连锁宾馆的干净。卫生间洗澡房地上的去水堵的很严重。总的来说对这宾馆的印象不太好。', 0)
('酒店的硬件我觉得很满意,总体来说比那个叫玉华苑的酒店好多了呢!个方面都蛮方便,不过服务方面要加大改进!!!!!!!!', 1)
('订的是豪华大床房，到那里后豪华房已经没有了，免费升级到行政大床房。过程中服务的态度还好，就是手续有点繁复，行政房需要到22层checkin除了行政房上网free，其他房间上网需要40元/小时80元/一天，免费升级到行政房上网也需要付费。之前住过豪华双人房，感觉和行政大床房没有太大差别，房间大小和装修差不多。这家宾馆最舒服的一点就是浴室比一般宾馆大。总体来说，住过这家宾馆两次，装修和房间大小包括浴室在内，在上海四星级宾馆里来说还算不错的。', 1)

In [24]:
import torch

tokenizer = AutoTokenizer.from_pretrained('hfl/rbt3')


def collate_fn(batch):
    texts = [i[0] for i in batch]
    labels = [i[1] for i in batch]

    inputs = tokenizer(texts, max_length=128, padding="max_length", truncation=True, return_tensors="pt")
    # print(inputs)
    inputs['labels'] = torch.tensor(labels)

    return inputs

In [25]:
from torch.utils.data import DataLoader

trainloader = DataLoader(train_set, batch_size=32, shuffle=True, collate_fn=collate_fn)
validloader = DataLoader(valid_set, batch_size=64, shuffle=True, collate_fn=collate_fn)

In [26]:
next(enumerate(trainloader))[1]

{'input_ids': tensor([[ 101, 1283,  674,  ...,    0,    0,    0],
        [ 101,  679, 7231,  ...,    0,    0,    0],
        [ 101, 1041, 1071,  ...,    0,    0,    0],
        ...,
        [ 101, 6983, 2421,  ...,    0,    0,    0],
        [ 101, 2769, 3221,  ..., 2792,  809,  102],
        [ 101, 2769,  738,  ..., 2523, 3191,  102]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'labels': tensor([0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 1, 1])}

## 创建模型

In [27]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained('hfl/rbt3')
if torch.cuda.is_available():
    model = model.cuda()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hfl/rbt3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [28]:

from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=2e-5)

In [29]:
def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in validloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
            output = model(**batch)
            pred = torch.argmax(output.logits, dim=-1)
            acc_num += (pred.long() == batch['labels'].long()).float().sum()
    return acc_num / len(validloader.dataset)


def train(epoch=3, log_step=100):
    global_step = 0
    for ep in range(epoch):
        model.train()
        for batch in trainloader:
            if torch.cuda.is_available():
                batch = {k: v.cuda() for k, v in batch.items()}
            optimizer.zero_grad()
            output = model(**batch)
            output.loss.backward()
            optimizer.step()
            if global_step % log_step == 0:
                print(f"ep: {ep}, global_step: {global_step}, loss: {output.loss.item()}")
            global_step += 1
        acc = evaluate()
        print(f"ep: {ep}, global_step: {global_step}, acc: {acc}")

In [30]:
train()

ep: 0, global_step: 0, loss: 0.6275644898414612
ep: 0, global_step: 100, loss: 0.26984158158302307
ep: 0, global_step: 200, loss: 0.22550217807292938
ep: 0, global_step: 219, acc: 0.8969072103500366
ep: 1, global_step: 300, loss: 0.22268180549144745
ep: 1, global_step: 400, loss: 0.21390141546726227
ep: 1, global_step: 438, acc: 0.9046391248703003
ep: 2, global_step: 500, loss: 0.07370308041572571
ep: 2, global_step: 600, loss: 0.2798287868499756
ep: 2, global_step: 657, acc: 0.9046391248703003

In [34]:
sen = "我很喜欢这个商品"
sen = "我不想再购买这个商品了"
model.eval()
with torch.inference_mode():
    inputs = tokenizer(sen, return_tensors="pt")
    inputs = {k: v.cuda() for k, v in inputs.items()}
    output = model(**inputs)
    pred = torch.argmax(output.logits, dim=-1)
    print(f"输入：{sen}，预测结果：{pred.item()}")

输入：我不想再购买这个商品了，预测结果：0

In [42]:
from transformers import pipeline

model.config.id2label = {0: "负向", 1: "正向"}
pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

Device set to use cuda:0

In [43]:

pipe("我非常喜欢这个商品")

[{'label': '正向', 'score': 0.9427462816238403}]